package com.example.cachuelosfrontend.model;

// Generated 05-oct-2014 14:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Cachuelostate generated by hbm2java
 */
@Entity
@Table(name = "cachuelostate"
      , catalog = "cachuelos")
@XmlRootElement
public class Cachuelostate implements java.io.Serializable
{

   private Integer idCachueloState;
   private String name;
   private String description;
   private Set<Cachuelo> cachuelos = new HashSet<Cachuelo>(0);

   public Cachuelostate()
   {
   }

   public Cachuelostate(String name)
   {
      this.name = name;
   }

   public Cachuelostate(String name, String description, Set<Cachuelo> cachuelos)
   {
      this.name = name;
      this.description = description;
      this.cachuelos = cachuelos;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idCachueloState", unique = true, nullable = false)
   public Integer getIdCachueloState()
   {
      return this.idCachueloState;
   }

   public void setIdCachueloState(Integer idCachueloState)
   {
      this.idCachueloState = idCachueloState;
   }

   @Column(name = "name", nullable = false, length = 20)
   public String getName()
   {
      return this.name;
   }

   public void setName(String name)
   {
      this.name = name;
   }

   @Column(name = "description", length = 300)
   public String getDescription()
   {
      return this.description;
   }

   public void setDescription(String description)
   {
      this.description = description;
   }

   @XmlTransient  
   @JsonIgnore
   @OneToMany(fetch = FetchType.LAZY, mappedBy = "cachuelostate")
   public Set<Cachuelo> getCachuelos()
   {
      return this.cachuelos;
   }

   public void setCachuelos(Set<Cachuelo> cachuelos)
   {
      this.cachuelos = cachuelos;
   }

   public String toString()
   {
      StringBuilder buffer = new StringBuilder();
      buffer.append(name);
      return buffer.toString();
   }

}
