package com.example.cachuelosfrontend.model;
// Generated 05-oct-2014 14:18:06 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Digitalizeddocument generated by hbm2java
 */
@Entity
@Table(name="digitalizeddocument"
    ,catalog="cachuelos"
)
public class Digitalizeddocument  implements java.io.Serializable {


     private Integer idDigitalizedDocument;
     private Typecachuelo typecachuelo;
     private User user;
     private String name;
     private String description;
     private String urlImage;

    public Digitalizeddocument() {
    }

	
    public Digitalizeddocument(Typecachuelo typecachuelo, User user, String name) {
        this.typecachuelo = typecachuelo;
        this.user = user;
        this.name = name;
    }
    public Digitalizeddocument(Typecachuelo typecachuelo, User user, String name, String description, String urlImage) {
       this.typecachuelo = typecachuelo;
       this.user = user;
       this.name = name;
       this.description = description;
       this.urlImage = urlImage;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDigitalizedDocument", unique=true, nullable=false)
    public Integer getIdDigitalizedDocument() {
        return this.idDigitalizedDocument;
    }
    
    public void setIdDigitalizedDocument(Integer idDigitalizedDocument) {
        this.idDigitalizedDocument = idDigitalizedDocument;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTypeCachuelo", nullable=false)
    public Typecachuelo getTypecachuelo() {
        return this.typecachuelo;
    }
    
    public void setTypecachuelo(Typecachuelo typecachuelo) {
        this.typecachuelo = typecachuelo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUser", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=600)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="urlImage", length=300)
    public String getUrlImage() {
        return this.urlImage;
    }
    
    public void setUrlImage(String urlImage) {
        this.urlImage = urlImage;
    }




}


