package com.example.cachuelosfrontend.model;

// Generated 05-oct-2014 14:18:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Imagecachuelo generated by hbm2java
 */
@Entity
@Table(name = "imagecachuelo", catalog = "cachuelos")
public class Imagecachuelo implements java.io.Serializable {

	private Integer idImageCachuelo;
	private Cachuelo cachuelo;
	private String urlImage;

	public Imagecachuelo() {
	}

	public Imagecachuelo(Cachuelo cachuelo, String urlImage) {
		this.cachuelo = cachuelo;
		this.urlImage = urlImage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idImageCachuelo", unique = true, nullable = false)
	public Integer getIdImageCachuelo() {
		return this.idImageCachuelo;
	}

	public void setIdImageCachuelo(Integer idImageCachuelo) {
		this.idImageCachuelo = idImageCachuelo;
	}

	@XmlTransient
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCachuelo", nullable = false)
	public Cachuelo getCachuelo() {
		return this.cachuelo;
	}

	public void setCachuelo(Cachuelo cachuelo) {
		this.cachuelo = cachuelo;
	}

	@Column(name = "urlImage", nullable = false, length = 300)
	public String getUrlImage() {
		return this.urlImage;
	}

	public void setUrlImage(String urlImage) {
		this.urlImage = urlImage;
	}

	public String toString() {
		StringBuilder buffer = new StringBuilder();
		buffer.append(urlImage);
		return buffer.toString();
	}
}
