package com.example.cachuelosfrontend.model;

// Generated 05-oct-2014 14:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * Userlocationbytime generated by hbm2java
 */
@Entity
@Table(name = "userlocationbytime"
      , catalog = "cachuelos")
@XmlRootElement
public class Userlocationbytime implements java.io.Serializable
{

   private Integer idUserLocationByTime;
   private User user;
   private double lat;
   private double lng;
   private Date dateAndTime;

   public Userlocationbytime()
   {
   }

   public Userlocationbytime(User user, double lat, double lng, Date dateAndTime)
   {
      this.user = user;
      this.lat = lat;
      this.lng = lng;
      this.dateAndTime = dateAndTime;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idUserLocationByTime", unique = true, nullable = false)
   public Integer getIdUserLocationByTime()
   {
      return this.idUserLocationByTime;
   }

   public void setIdUserLocationByTime(Integer idUserLocationByTime)
   {
      this.idUserLocationByTime = idUserLocationByTime;
   }

   @ManyToOne(fetch = FetchType.EAGER)
   @JoinColumn(name = "idUser", nullable = false)
   public User getUser()
   {
      return this.user;
   }

   public void setUser(User user)
   {
      this.user = user;
   }

   @Column(name = "lat", nullable = false, precision = 22, scale = 0)
   public double getLat()
   {
      return this.lat;
   }

   public void setLat(double lat)
   {
      this.lat = lat;
   }

   @Column(name = "lng", nullable = false, precision = 22, scale = 0)
   public double getLng()
   {
      return this.lng;
   }

   public void setLng(double lng)
   {
      this.lng = lng;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "dateAndTime", nullable = false, length = 19)
   public Date getDateAndTime()
   {
      return this.dateAndTime;
   }

   public void setDateAndTime(Date dateAndTime)
   {
      this.dateAndTime = dateAndTime;
   }

}
