package com.example.cachuelosfrontend.model;
// Generated 05-oct-2014 14:18:06 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;

/**
 * WorkerbytypecachueloId generated by hbm2java
 */
@Embeddable
public class WorkerbytypecachueloId  implements java.io.Serializable {


     private int idUserWorker;
     private int idTypeCachuelo;

    public WorkerbytypecachueloId() {
    }

    public WorkerbytypecachueloId(int idUserWorker, int idTypeCachuelo) {
       this.idUserWorker = idUserWorker;
       this.idTypeCachuelo = idTypeCachuelo;
    }
   


    @GeneratedValue
    @Column(name="idUserWorker", nullable=false)
    public int getIdUserWorker() {
        return this.idUserWorker;
    }
    
    public void setIdUserWorker(int idUserWorker) {
        this.idUserWorker = idUserWorker;
    }


    @GeneratedValue
    @Column(name="idTypeCachuelo", nullable=false)
    public int getIdTypeCachuelo() {
        return this.idTypeCachuelo;
    }
    
    public void setIdTypeCachuelo(int idTypeCachuelo) {
        this.idTypeCachuelo = idTypeCachuelo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WorkerbytypecachueloId) ) return false;
		 WorkerbytypecachueloId castOther = ( WorkerbytypecachueloId ) other; 
         
		 return (this.getIdUserWorker()==castOther.getIdUserWorker())
 && (this.getIdTypeCachuelo()==castOther.getIdTypeCachuelo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUserWorker();
         result = 37 * result + this.getIdTypeCachuelo();
         return result;
   }   


}


