package com.example.cachuelosfrontend.model;

// Generated 05-oct-2014 14:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Zone generated by hbm2java
 */
@Entity
@Table(name = "zone"
      , catalog = "cachuelos")
@XmlRootElement
public class Zone implements java.io.Serializable
{

   private Integer idZone;
   private float lat;
   private float lng;
   private String name;
   private float radius;
   private int cachCount;
   private Set<User> users = new HashSet<User>(0);

   public Zone()
   {
   }

   public Zone(float lat, float lng, String name, float radius)
   {
      this.lat = lat;
      this.lng = lng;
      this.name = name;
      this.radius = radius;
   }

   public Zone(float lat, float lng, String name, float radius, Set<User> users)
   {
      this.lat = lat;
      this.lng = lng;
      this.name = name;
      this.radius = radius;
      this.users = users;
   
   }
   
   @Transient
	public int getCachCount() {
		return cachCount;
	}

	public void setCachCount(int cachCount) {
		this.cachCount = cachCount;
	}

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "idZone", unique = true, nullable = false)
   public Integer getIdZone()
   {
      return this.idZone;
   }

   public void setIdZone(Integer idZone)
   {
      this.idZone = idZone;
   }

   @Column(name = "lat", nullable = false, precision = 12, scale = 0)
   public float getLat()
   {
      return this.lat;
   }

   public void setLat(float lat)
   {
      this.lat = lat;
   }

   @Column(name = "lng", nullable = false, precision = 12, scale = 0)
   public float getLng()
   {
      return this.lng;
   }

   public void setLng(float lng)
   {
      this.lng = lng;
   }

   @Column(name = "name", nullable = false, length = 200)
   public String getName()
   {
      return this.name;
   }

   public void setName(String name)
   {
      this.name = name;
   }

   @Column(name = "radius", nullable = false, precision = 12, scale = 0)
   public float getRadius()
   {
      return this.radius;
   }

   public void setRadius(float radius)
   {
      this.radius = radius;
   }

   @XmlTransient
   @JsonIgnore
   @OneToMany(fetch = FetchType.LAZY, mappedBy = "zone")
   public Set<User> getUsers()
   {
      return this.users;
   }

   public void setUsers(Set<User> users)
   {
      this.users = users;
   }
	public String toString() {
		StringBuilder buffer = new StringBuilder();
		buffer.append(name);
		return buffer.toString();
	}

}
