package com.example.cachuelosadmin.model;
// Generated 29-oct-2014 12:58:38 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="Users"
    ,catalog="cachuelos"
)
public class Users  implements java.io.Serializable {


     private String username;
     private String passwd;
     private Set<Userroles> userroleses = new HashSet<Userroles>(0);

    public Users() {
    }

	
    public Users(String username, String passwd) {
        this.username = username;
        this.passwd = passwd;
    }
    public Users(String username, String passwd, Set<Userroles> userroleses) {
       this.username = username;
       this.passwd = passwd;
       this.userroleses = userroleses;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length = 255)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="passwd", nullable=false, length = 255)
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<Userroles> getUserroleses() {
        return this.userroleses;
    }
    
    public void setUserroleses(Set<Userroles> userroleses) {
        this.userroleses = userroleses;
    }

    public String toString() {

		StringBuilder buffer = new StringBuilder();
		buffer.append(username);
		return buffer.toString();
	}


}


