package com.example.cachuelosadmin.model;
// Generated 29-oct-2014 12:58:38 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Userroles generated by hbm2java
 */
@Entity
@Table(name="UserRoles"
    ,catalog="cachuelos"
)
public class Userroles  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private String userRoles;

    public Userroles() {
    }

    public Userroles(Users users, String userRoles) {
       this.users = users;
       this.userRoles = userRoles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="userRoles", nullable=false, length = 255)
    public String getUserRoles() {
        return this.userRoles;
    }
    
    public void setUserRoles(String userRoles) {
        this.userRoles = userRoles;
    }



    public String toString() {

		StringBuilder buffer = new StringBuilder();
		buffer.append(users);
		buffer.append(" ").append(userRoles);
		return buffer.toString();
	}
}


